#ifndef  TOKEN_TYPE_H

#define TOKEN_TYPE_H

enum class TokenType
{
	EQUALS, PLUS, MINUS, PROD, DIV,
	EQUAL_EQUAL, NOT_EQUAL, NOT,
	LESS_THAN, GREATER_THAN,
	LESS_EQUAL, GREATER_EQUAL,
	AND, OR,
	IF, THEN, ELSE,
	WHILE, DO, DONE,

	OPEN_PAREN, CLOSE_PAREN,
	OPEN_BRACKET, CLOSE_BRACKET,

	NUMBER, VARIABLE,

	PRINT, READ,

	END_OF_FILE, END_OF_LINE
};

#endif // ! TOKEN_TYPE_H
